## Import NumPy and Pandas

In [1]:
import numpy as np
import pandas as pd

## Get "Absenteeism-data.csv" original file

In [2]:
raw_csv_data = pd.read_csv("Absenteeism-data.csv")

## Display data

In [3]:
#raw_csv_data

## Create a copy from the original file

In [4]:
df = raw_csv_data.copy()

In [5]:
#df

## Display all columns and rows

In [6]:
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [7]:
#display(df)

## Display informations about the data

In [8]:
#df.info()

## Drop 'ID' column

In [9]:
df = df.drop(['ID'], axis = 1)

In [10]:
#df

## Extract 'Reasons for Absence' column

### This list shows the categories of absenteeism. Each number represents a category

In [11]:
sorted(df['Reason for Absence'].unique())

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28]

## Get dummies

In [12]:
reason_columns = pd.get_dummies(df['Reason for Absence'])

In [13]:
#reason_columns

## Check if some rows have missing values

#### 0: missing value || 1: single value

In [14]:
reason_columns['check'] = reason_columns.sum(axis = 1)

In [15]:
#reason_columns

### Check the vertical axis length

In [16]:
reason_columns['check'].sum(axis = 0)

700

### Check if we have different values from the "check" column

In [17]:
reason_columns['check'].unique()

array([1])

### Delete "check" column after the verifications

In [18]:
reason_columns = reason_columns.drop(['check'], axis = 1)

In [19]:
#reason_columns

## Delete column 0 from "reason_columns" variable

In [20]:
reason_columns = pd.get_dummies(df['Reason for Absence'], drop_first = True)

In [21]:
#reason_columns

## Grouping the "Reason for Absence" columns

### Three steps:
- <ins>First step:</ins> add dummy variables on the current state of DateFrame (avoid duplicate information between "Reason for Absence" column and dummy variables).
- <ins>Second step:</ins> grouping the variables into the DataFrame (create group for each category).
- <ins>Third step:</ins> concatenate column values

### First step

In [22]:
df.columns.values

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets',
       'Absenteeism Time in Hours'], dtype=object)

In [23]:
reason_columns.columns.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 21, 22, 23, 24, 25, 26, 27, 28])

In [24]:
df = df.drop(['Reason for Absence'], axis = 1)

In [25]:
#df

### Second step

In [26]:
reason_type_1 = reason_columns.loc[:, 1:14].max(axis = 1)
reason_type_2 = reason_columns.loc[:, 14:17].max(axis = 1)
reason_type_3 = reason_columns.loc[:, 18:21].max(axis = 1)
reason_type_4 = reason_columns.loc[:, 22:28].max(axis = 1)

In [27]:
#reason_type_1

### Third step

In [29]:
df = pd.concat([df, reason_type_1, reason_type_2, reason_type_3, reason_type_4], axis = 1)

In [31]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  0  1  2  3  
0                          4  0  0  0  1  
1                          0  0  0  0  0  
2                          2  0  0  0  1  
3                          4  1  0  0  0  
4                          2  0  0  0  1

## Rename the reasons columns

In [32]:
df.columns.values

array(['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 0, 1, 2, 3],
      dtype=object)

In [34]:
columns_names = ['Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours', 'Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']

In [35]:
df.columns = columns_names

In [36]:
df.head()

Date  Transportation Expense  Distance to Work  Age  \
0  07/07/2015                     289                36   33   
1  14/07/2015                     118                13   50   
2  15/07/2015                     179                51   38   
3  16/07/2015                     279                 5   39   
4  23/07/2015                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          1         2     1   
1                  239.554               31          1         1     0   
2                  239.554               31          1         0     0   
3                  239.554               24          1         2     0   
4                  239.554               30          1         2     1   

   Absenteeism Time in Hours  Reason_1  Reason_2  Reason_3  Reason_4  
0                          4         0         0         0         1  
1                          0         0         0         0         0  
2                          2         0         0         0         1  
3                          4         1         0         0         0  
4                          2         0         0         0         1

## Reorder columns

In [37]:
column_name_reordered = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Date', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours']

In [39]:
df = df[column_name_reordered]

In [40]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4        Date  Transportation Expense  \
0         0         0         0         1  07/07/2015                     289   
1         0         0         0         0  14/07/2015                     118   
2         0         0         0         1  15/07/2015                     179   
3         1         0         0         0  16/07/2015                     279   
4         0         0         0         1  23/07/2015                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

## 'Date' column

In [44]:
df_reason_mod = df.copy()

In [52]:
df_reason_mod['Date'] = pd.to_datetime(df_reason_mod['Date'], format = '%d/%m/%Y')

In [56]:
df_reason_mod['Date'].head()

0   2015-07-07
1   2015-07-14
2   2015-07-15
3   2015-07-16
4   2015-07-23
Name: Date, dtype: datetime64[ns]

### Check the 'Date' column Dtype

In [57]:
df_reason_mod.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype         
---  ------                     --------------  -----         
 0   Reason_1                   700 non-null    uint8         
 1   Reason_2                   700 non-null    uint8         
 2   Reason_3                   700 non-null    uint8         
 3   Reason_4                   700 non-null    uint8         
 4   Date                       700 non-null    datetime64[ns]
 5   Transportation Expense     700 non-null    int64         
 6   Distance to Work           700 non-null    int64         
 7   Age                        700 non-null    int64         
 8   Daily Work Load Average    700 non-null    float64       
 9   Body Mass Index            700 non-null    int64         
 10  Education                  700 non-null    int64         
 11  Children                   700 non-null    int64         
 12  Pets    

## Extract month value from 'Date' column

In [59]:
df_reason_mod['Date'][0].month

7

In [61]:
list_months = []

In [63]:
df_reason_mod.shape

(700, 14)

In [64]:
for i in range(df_reason_mod.shape[0]):
    list_months.append(df_reason_mod['Date'][i].month)

In [68]:
len(list_months)

700

In [69]:
df_reason_mod['Month Value'] = list_months

In [71]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  
0         2     1                          4            7  
1         1     0                          0            7  
2         0     0                          2            7  
3         2     0                          4            7  
4         2     1                          2            7

# Extract the day of the week

In [79]:
df_reason_mod['Date'][699].weekday()

3

In [78]:
df_reason_mod['Date'][699]

Timestamp('2018-05-31 00:00:00')

In [82]:
def date_to_weekday(date_value):
    return date_value.weekday()

In [83]:
df_reason_mod['Day of the Week'] = df_reason_mod['Date'].apply(date_to_weekday)

In [84]:
df_reason_mod.head()

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0         0         0         0         1 2015-07-07                     289   
1         0         0         0         0 2015-07-14                     118   
2         0         0         0         1 2015-07-15                     179   
3         1         0         0         0 2015-07-16                     279   
4         0         0         0         1 2015-07-23                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          1   
1                13   50                  239.554               31          1   
2                51   38                  239.554               31          1   
3                 5   39                  239.554               24          1   
4                36   33                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

## 'Education' column

In [85]:
df_reason_mod['Education'].unique()

array([1, 3, 2, 4])

#### Four categories of Education:
1. High School
2. Graduate
3. Postgraduate
4. a master or a doctor

In [87]:
df_reason_mod['Education'].value_counts()

1    583
3     73
2     40
4      4
Name: Education, dtype: int64

#### Separating by two graduate types:
0. High school
1. Graduate, Postgraduate and a master or a doctor

In [91]:
df_reason_mod['Education'] = df_reason_mod['Education'].map({1:0, 2:1, 3:1, 4:1})

In [92]:
df_reason_mod['Education'].unique()

array([0, 1])

In [93]:
df_reason_mod['Education'].value_counts()

0    583
1    117
Name: Education, dtype: int64

In [97]:
df_reason_mod.head(50)

Reason_1  Reason_2  Reason_3  Reason_4       Date  Transportation Expense  \
0          0         0         0         1 2015-07-07                     289   
1          0         0         0         0 2015-07-14                     118   
2          0         0         0         1 2015-07-15                     179   
3          1         0         0         0 2015-07-16                     279   
4          0         0         0         1 2015-07-23                     289   
5          0         0         0         1 2015-10-07                     179   
6          0         0         0         1 2015-07-17                     361   
7          0         0         0         1 2015-07-24                     260   
8          0         0         1         0 2015-06-07                     155   
9          0         0         0         1 2015-07-13                     235   
10         1         0         0         0 2015-07-20                     260   
11         1         0         0         0 2015-07-14                     260   
12         1         0         0         0 2015-07-15                     260   
13         1         0         0         0 2015-07-15                     179   
14         0         0         0         1 2015-07-15                     179   
15         1         1         0         0 2015-07-17                     246   
16         0         0         0         1 2015-07-17                     179   
17         0         0         1         0 2015-07-27                     179   
18         1         0         0         0 2015-07-30                     189   
19         0         0         0         1 2015-05-08                     248   
20         1         0         0         0 2015-12-08                     330   
21         1         0         0         0 2015-03-08                     179   
22         1         0         0         0 2015-10-08                     361   
23         0         0         0         1 2015-08-14                     260   
24         0         0         1         0 2015-08-17                     289   
25         0         0         0         1 2015-08-24                     361   
26         0         0         0         1 2015-04-08                     289   
27         0         0         0         1 2015-12-08                     157   
28         0         0         1         0 2015-08-19                     289   
29         0         0         0         1 2015-08-28                     179   
30         0         0         1         0 2015-08-17                     179   
31         0         0         1         0 2015-08-27                     235   
32         0         0         0         1 2015-08-27                     235   
33         0         0         1         0 2015-08-17                     235   
34         0         0         0         1 2015-08-17                     179   
35         0         0         0         1 2015-08-17                     361   
36         0         0         0         1 2015-04-08                     289   
37         1         0         0         0 2015-08-20                     291   
38         0         0         0         1 2015-08-21                     235   
39         0         0         0         1 2015-08-28                     260   
40         0         0         0         1 2015-01-09                     184   
41         0         0         0         1 2015-07-09                     118   
42         0         0         0         1 2015-01-09                     179   
43         0         0         1         0 2015-08-09                     235   
44         0         0         0         1 2015-09-09                     155   
45         0         0         0         1 2015-09-13                     118   
46         0         0         0         1 2015-09-14                     179   
47         0         0         0         1 2015-09-24                     291   
48         0         0         0   